select
    user_id,
    display_name,
    reputation,
    user_created_at,
    last_access_at,
    last_activity_at,
    location,
    profile_views,
    up_votes,
    down_votes,
    question_count,
    answer_count,
    comment_count,
    badge_count,
    gold_badge_count,
    silver_badge_count,
    bronze_badge_count,
    tag_based_badge_count,
    answers_given_count,
    accepted_answers_count,
    answer_acceptance_rate,
    {{ categorize_reputation('reputation') }} as expertise_level,
    {{ categorize_activity_status('days_since_last_activity') }} as activity_status,
    days_since_last_activity
from {{ ref('wh_users') }}
